name: Release

on:
  push:
    branches:
      - resourcepack

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Create ZIP
        run: zip -r /resourcepack.zip * -x .git** .gitatributes README.md
      - name: Find version
        id: version
        run: echo "id=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Publish release
        run: gh release create $VERSION '/resourcepack.zip#Resource pack'
        env:
          VERSION: ${{ steps.version.outputs.id }}